sudo: false
language: node_js
node_js:
  - 'stable'
  - '4.0'
  - '0.12'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm install node-gyp -g
before_script:
  - npm install -g mocha
