language: node_js
node_js:
  - 'stable'
  - '4.0'
  - '0.12'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - npm install node-gyp -g
  - export CC="gcc-4.9" CXX="g++-4.9"
before_script:
  - npm install -g mocha
